# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('publishedDate', models.DateTimeField(blank=True, null=True)),
                ('cachedBlogRating', models.PositiveIntegerField(default=0)),
                ('cachedMembersNumber', models.PositiveIntegerField(default=0)),
                ('cachedPostsNumber', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('publishedDate', models.DateTimeField(blank=True, null=True)),
                ('path0', models.PositiveIntegerField(default=0)),
                ('path1', models.PositiveIntegerField(default=0, null=True)),
                ('path2', models.PositiveIntegerField(default=0, null=True)),
                ('path3', models.PositiveIntegerField(default=0, null=True)),
                ('path4', models.PositiveIntegerField(default=0, null=True)),
                ('cachedRating', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('publishedDate', models.DateTimeField(blank=True, null=True)),
                ('cachedRating', models.PositiveIntegerField(default=0)),
                ('cachedCommentsNumber', models.PositiveIntegerField(default=0)),
                ('cachedSubscriptionsNumber', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField()),
                ('cachedUserRating', models.PositiveIntegerField(default=0)),
                ('cachedCommentsNumber', models.PositiveIntegerField(default=0)),
                ('cachedPostsNumber', models.PositiveIntegerField(default=0)),
                ('cachedSubscriptionsForPostNumber', models.PositiveIntegerField(default=0)),
                ('cachedSubscriptionsForBlogNumber', models.PositiveIntegerField(default=0)),
                ('cachedSubscriptionsForUserNumber', models.PositiveIntegerField(default=0)),
                ('cachedFollowersNumber', models.PositiveIntegerField(default=0)),
                ('followedBlogs', models.ManyToManyField(to='blog.Blog')),
                ('followedPosts', models.ManyToManyField(to='blog.Post')),
                ('followedUsers', models.ManyToManyField(to='blog.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteForComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.NullBooleanField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteForPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.NullBooleanField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
