# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followedBlogs',
            field=models.ManyToManyField(blank=True, to='blog.Blog'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followedPosts',
            field=models.ManyToManyField(blank=True, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followedUsers',
            field=models.ManyToManyField(blank=True, to='blog.Profile'),
        ),
    ]
