# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160308_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=models.CharField(max_length=200),
        ),
    ]
