# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160515_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('cachedTagNumber', models.PositiveIntegerField(default=0)),
                ('posts', models.ManyToManyField(blank=True, to='blog.Post')),
            ],
        ),
    ]
