# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160308_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='html_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
