# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160310_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='positive',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='negative',
        ),
    ]
