# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160618_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteforpost',
            name='like',
            field=models.SmallIntegerField(default=0),
        ),
    ]
