# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160310_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='html_content',
            new_name='HTMLContent',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='publishedDate',
        ),
    ]
