# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160310_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('avatar', models.CharField(max_length=200)),
                ('createdDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
