# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160618_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cachedBlogRating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cachedRating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='cachedRating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cachedUserRating',
            field=models.IntegerField(default=0),
        ),
    ]
