# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='createdDate',
            new_name='publishedDate',
        ),
    ]
