# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20160311_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='members',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='posts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
