# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160218_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='negative',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='positive',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
